### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by bpires** [Gabriel-025/mywork-ignite#4]
Hey Gabriel,

Percebi algumas typos no projeto (sempre acontece, nada demais!) mas só sinalizando pra contribuir:

> Construa ~umaaplicação~ => uma aplicação
> ~GARANRTIR~ MINHA VAGA => GARANTIR

Grande abraço!

**Comment by Gabriel-025** [comment]
Opa, cara obrigado mesmo, por mais dev's assim ajudando a comunidade.
Grato pelo feedback!
